version: '3.8'
volumes:
    email-data-volume:
services:
    email-sender-db:
        image: postgres:12.3
        volumes:
            # data vollume
            - email-data-volume:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            - POSTGRES_USERS=postgres
            - POSTGRES_PASSWORD=postgres

    frontend:
        # nginx:1.18 is not working ->
        # nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
        image: nginx:1.17 
        volumes:
            - ./web:/usr/share/nginx/html/
        ports:
            - 80:80
    backend:
        image: python:3.6
        volumes:
            # Application
            - ./backend:/backend
        working_dir: /backend
        # this version also works -> 
        # command: chmod +x && ./backend_app.sh
        command: bash ./backend_app.sh
        ports:
            - 8080:8080